services:
  - type: web
    name: plpfinalproject-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        value: https://plpfinalproject.vercel.app
    healthCheckPath: /api/v2/test
    branch: main 